markdown: rdiscount
pygments: false
permalink:  /:year/:month/:day/:title/
paginate: 3
url: http://makehacklearn.org
title:        Make Hack Learn
description:  Learning to Hack One Inch at a Time
url_root:     http://makehacklearn.org
author:       Al Billings
author_short: albill
author_email: albill@openbuddha.com
feedburner_id: makehacklearn
disqus_id:    makehacklearn
disqus_username: albill
twitter_name: openbuddha
facebook_uid: 139700605
# Change the dir the individual category files are output to
category_dir: categories # Default is categories
# Title to be used when generating the individual category html files prefixed to category name
category_title_prefix: "categories"
navigation:
- text: Blog
  url: /index.html
  layout: post
- text: About me
  url: /about_me.html